In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\meswa\\OneDrive\\Desktop\\new file\\final_cle.csv")

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0.2,Company,TypeName,Ram,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,0,0,0,Apple,Ultrabook,8,Mac,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,Intel
1,1,1,1,Apple,Ultrabook,8,Mac,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,Intel
2,2,2,2,HP,Notebook,8,Other,1.86,30636.0000,0,0,141.211998,Intel Core i5,0,256,Intel
3,3,3,3,Apple,Ultrabook,16,Mac,1.83,135195.3360,0,1,220.534624,Intel Core i7,0,512,AMD
4,4,4,4,Apple,Ultrabook,8,Mac,1.37,96095.8080,0,1,226.983005,Intel Core i5,0,256,Intel

In [4]:
df.dtypes

Unnamed: 0.1      int64
Unnamed: 0        int64
Unnamed: 0.2      int64
Company             str
TypeName            str
Ram               int64
OpSys               str
Weight          float64
Price           float64
TouchScreen       int64
IPS               int64
PPI             float64
CPU_name            str
HDD               int64
SSD               int64
Gpu brand           str
dtype: object

In [5]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0.2,Company,TypeName,Ram,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,0,0,0,Apple,Ultrabook,8,Mac,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,Intel
1,1,1,1,Apple,Ultrabook,8,Mac,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,Intel
2,2,2,2,HP,Notebook,8,Other,1.86,30636.0000,0,0,141.211998,Intel Core i5,0,256,Intel
3,3,3,3,Apple,Ultrabook,16,Mac,1.83,135195.3360,0,1,220.534624,Intel Core i7,0,512,AMD
4,4,4,4,Apple,Ultrabook,8,Mac,1.37,96095.8080,0,1,226.983005,Intel Core i5,0,256,Intel

In [6]:
df = df.drop(["Unnamed: 0", "Unnamed: 0.1", "Unnamed: 0.2"], axis=1)

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Company'] = le.fit_transform(df['Company'])
df['TypeName'] = le.fit_transform(df['TypeName'])
df['OpSys'] = le.fit_transform(df['OpSys'])
df['CPU_name'] = le.fit_transform(df['CPU_name'])
df['Gpu brand'] = le.fit_transform(df['Gpu brand'])

In [8]:
df.head()

,Company,TypeName,Ram,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,1,4,8,0,1.37,71378.6832,0,1,226.983005,2,0,128,1
1,1,4,8,0,1.34,47895.5232,0,0,127.677940,2,0,0,1
2,7,3,8,1,1.86,30636.0000,0,0,141.211998,2,0,256,1
3,1,4,16,0,1.83,135195.3360,0,1,220.534624,3,0,512,0
4,1,4,8,0,1.37,96095.8080,0,1,226.983005,2,0,256,1

In [9]:
X = df.drop("Price", axis=1)
y = df["Price"]

In [10]:
X.head()

,Company,TypeName,Ram,OpSys,Weight,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,1,4,8,0,1.37,0,1,226.983005,2,0,128,1
1,1,4,8,0,1.34,0,0,127.677940,2,0,0,1
2,7,3,8,1,1.86,0,0,141.211998,2,0,256,1
3,1,4,16,0,1.83,0,1,220.534624,3,0,512,0
4,1,4,8,0,1.37,0,1,226.983005,2,0,256,1

In [11]:
y.head()

0     71378.6832
1     47895.5232
2     30636.0000
3    135195.3360
4     96095.8080
Name: Price, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1041, 12), (261, 12), (1041,), (261,))

In [14]:
df.columns.tolist()

['Company',
 'TypeName',
 'Ram',
 'OpSys',
 'Weight',
 'Price',
 'TouchScreen',
 'IPS',
 'PPI',
 'CPU_name',
 'HDD',
 'SSD',
 'Gpu brand']

In [15]:
X_train.dtypes

Company          int64
TypeName         int64
Ram              int64
OpSys            int64
Weight         float64
TouchScreen      int64
IPS              int64
PPI            float64
CPU_name         int64
HDD              int64
SSD              int64
Gpu brand        int64
dtype: object

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
best_model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
best_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score 
models = {
    "Linear": LinearRegression(),
    "DecisionTree": DecisionTreeRegressor(),
    "RandomForest": RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42),
    "KNN": KNeighborsRegressor(),
    "SVR": SVR(),
}

best_score = 0
best_model = " "

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = r2_score(y_test, y_pred)
    


    print(name, "R2 Score:", score)
    
    if score > best_score:
        best_score = score
        best_model = name

print("\nBest Model:", best_model)

Linear R2 Score: 0.685910799254843
DecisionTree R2 Score: 0.76783545144928

RandomForest R2 Score: 0.8092002226221059
KNN R2 Score: 0.7416648050010872
SVR R2 Score: -0.024581715906303536

Best Model: RandomForest

In [21]:
df.to_csv("C:\\Users\\meswa\\OneDrive\\Desktop\\new file\\six_cle.csv", index=False)